image: obarun/base:latest

before_script:
  - pacman -Syu --noconfirm
  - pacman -S util-linux autoconf automake binutils bison fakeroot file findutils flex gawk gcc gettext grep groff gzip libtool m4 make patch pkgconf sed sudo texinfo which
  
build:
  stage: build
  script:
  - ./configure --disable-allstatic
  - make -j9
  - make -j9 install-html DESTDIR=gitlab-ci
  - make -j9 man
  - make -j9 install DESTDIR=gitlab-ci
  - make -j9 install-man DESTDIR=gitlab-ci

    
