image: obarun/base:latest

before_script:
  - pacman -Syu $(pacman -Sqg base-devel|grep -v systemd) --noconfirm
 
build:
  stage: build
  script:
  - ./configure --disable-allstatic
  - make -j9
  - make -j9 install-html DESTDIR=gitlab-ci
  - make -j9 man
  - make -j9 install DESTDIR=gitlab-ci
  - make -j9 install-man DESTDIR=gitlab-ci

    
